services:
  db:
    image: postgres:16
    container_name: file_share_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fileshare
      POSTGRES_USER: fileshare
      POSTGRES_PASSWORD: fileshare
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: